spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0709
  data:
    redis:
      host: 192.168.44.128
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 0
          max-wait: 5000
      connect-timeout: 3000
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名匹配
  mapper-locations: classpath:mapper/*.xml  # XML 映射文件路径（classpath:mapper/ 表示 resources/mapper/）
  type-aliases-package: com.gvc.pojo  # 实体类别名（配置后，XML 中 resultType 可直接写类名，无需全类名）